question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
{"text":"Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.","answer":"False"},
{"text":"Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.","answer":"False"},
{"text":"The Republic of Malta is the smallest microstate worldwide.","answer":"False"},
{"text":"Pointers were not used in the original C programming language; they were added later on in C++.","answer":"False"},
{"text":"Alaska is the largest state in the United States.","answer":"True"},
{"text":"Denmark has a monarch.","answer":"True"},
{"text":"In Team Fortress 2, being disguised as a scout or medic results in a speed boost.","answer":"False"},
{"text":"In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.","answer":"True"},
{"text":"The United States of America declared their independence from the British Empire on July 4th, 1776.","answer":"True"},
{"text":"The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.","answer":"False"},
{"text":"In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.","answer":"False"},
{"text":"Ana was added as a new hero for the game Overwatch on July 19th, 2016.","answer":"True"},
{"text":"Time on Computers is measured via the EPOX System.","answer":"False"},
{"text":"In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.","answer":"False"},
{"text":"In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.","answer":"True"},
{"text":"In &quot;Undertale&quot;, the main character of the game is Sans.","answer":"False"},
{"text":"In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.","answer":"True"},
{"text":"Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.","answer":"True"},
{"text":"&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.","answer":"True"},
{"text":"The Harry Potter series of books, combined, are over 1,000,000 words in length.","answer":"True"}
]

